"""rate limit buckets

Revision ID: 51d87fdefb28
Revises: 4cd2a8fc4580
Create Date: 2026-08-14 12:51:39.627821
"""

from alembic import op
import sqlalchemy as sa


revision = '51d87fdefb28'
down_revision = '4cd2a8fc4580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bucket', sa.String(length=160), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket', 'window_start')
    )
    with op.batch_alter_table('rate_limits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_limits_bucket'), ['bucket'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rate_limits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_limits_bucket'))

    op.drop_table('rate_limits')
    # ### end Alembic commands ###
